---
broker:
  name: broker-name
  host: voltha-kafka.default.svc.cluster.local:9092
  description: The kafka broker
  topics: [voltha.kpis, onos.kpis, importer.kpis]
logger:
  loglevel: debug
  host: voltha-kafka.default.svc.cluster.local:9092
target:
  type: prometheus-target
  name: http-server
  port: 8080
  description: http target for prometheus
